model8:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
   type: effort_controllers/JointPositionController
   joint: J1
   pid: {p: 1, i: 0.0, d: 0.0}
  joint2_position_controller:
   type: effort_controllers/JointPositionController
   joint: J2
   pid: {p: 1, i: 0.0, d: 0.0}
  joint3_position_controller:
   type: effort_controllers/JointPositionController
   joint: J3
   pid: {p: 1, i: 0.0, d: 0.0}
  joint4_position_controller:
   type: effort_controllers/JointPositionController
   joint: J4
   pid: {p: 1, i: 0.0, d: 0.0}
  joint5_position_controller:
   type: effort_controllers/JointPositionController
   joint: J5
   pid: {p: 1, i: 0.0, d: 0.0}
  joint6_position_controller:
   type: effort_controllers/JointPositionController
   joint: J6
   pid: {p: 1, i: 0.0, d: 0.0}
  joint7_position_controller:
   type: effort_controllers/JointPositionController
   joint: J7
   pid: {p: 1, i: 0.0, d: 0.0}
  joint8_position_controller:
   type: effort_controllers/JointPositionController
   joint: J8
   pid: {p: 1, i: 0.0, d: 0.0}
  joint9_position_controller:
   type: effort_controllers/JointPositionController
   joint: J9
   pid: {p: 1, i: 0.0, d: 0.0}
  joint10_position_controller:
   type: effort_controllers/JointPositionController
   joint: J10
   pid: {p: 1, i: 0.0, d: 0.0}
